In [1]:
import scipy.io as scio #这是v3.7之前的版本需要用的格式
import hdf5storage as hdf
import pandas as pd
import numpy as np
import scipy
import random
import os

import matplotlib.pyplot as plt

In [761]:
# load data
dataPath = './Spatial/Spatial/processed_data/'
real = hdf.loadmat(dataPath+'real_22.mat')
imag = hdf.loadmat(dataPath+'imag_22.mat') # mat文件读入的时候是list类型


In [753]:
real_orig = real['real_pf']
imag_orig = imag['imag_pf']

In [754]:
real_orig.shape

(15, 300, 10240)

In [755]:
real = real_orig.reshape([15*300,10240])
imag = imag_orig.reshape([15*300,10240])

In [756]:
# 只取其中前10个分类
real10 = real[0:3000,:]
imag10 = imag[0:3000,:]

In [757]:
print(real10.shape)
imag10.shape

(3000, 10240)


(3000, 10240)

In [758]:
num_of_sample = len(real10)

In [763]:
# PATH = './Spatial/non_zero_vector/22db/'

In [760]:
# 合并实部和虚部，形成三维矩阵，生成所需数据集
def img_generate(real, imag, save_path, begin, end):
    for i in range(begin,end):
        # a = (np.array([real[i], imag[i]])).transpose(1,2,0) # 修剪好形状的单个样本
        a = (np.array([real[i], imag[i]])).transpose(1,0)
        # b = b.append(a.transpose(1,2,0))
        np.save(file = save_path+"%d.npy"%(i+1),arr = a)

# 合并样本的实部和虚部
path1 = PATH+'d1/'
path2 = PATH+'d2/'
path3 = PATH+'d3/'
path4 = PATH+'d4/'
path5 = PATH+'d5/'
path6 = PATH+'d6/'
path7 = PATH+'d7/'
path8 = PATH+'d8/'
path9 = PATH+'d9/'
path10 = PATH+'d10/'

img_generate(real10, imag10, path1, 0, 300)
img_generate(real10, imag10, path2, 300, 600)
img_generate(real10, imag10, path3, 600, 900)
img_generate(real10, imag10, path4, 900, 1200)
img_generate(real10, imag10, path5, 1200, 1500)
img_generate(real10, imag10, path6, 1500, 1800)
img_generate(real10, imag10, path7, 1800, 2100)
img_generate(real10, imag10, path8, 2100, 2400)
img_generate(real10, imag10, path9, 2400, 2700)
img_generate(real10, imag10, path10, 2700, 3000)

In [26]:
# 合并版预处理，存储到non_zero_vector
# load data
dataPath = './Spatial/Spatial/processed_data/'
real = hdf.loadmat(dataPath+'real_0.mat')
imag = hdf.loadmat(dataPath+'imag_0.mat') # mat文件读入的时候是list类型

real_orig = real['real_pf']
imag_orig = imag['imag_pf']

real = real_orig.reshape([15*300,10240])
imag = imag_orig.reshape([15*300,10240])

# 只取其中前10个分类
real10 = real[0:3000,:]
imag10 = imag[0:3000,:]

print(real10)

num_of_sample = len(real10)

PATH = './Spatial/non_zero_vector/0db/'

# 合并实部和虚部，形成三维矩阵，生成所需数据集
def img_generate(real, imag, save_path, begin, end):
    for i in range(begin,end):
        # a = (np.array([real[i], imag[i]])).transpose(1,2,0) # 修剪好形状的单个样本
        a = (np.array([real[i], imag[i]])).transpose(1,0)
        # b = b.append(a.transpose(1,2,0))
        np.save(file = save_path+"%d.npy"%(i+1),arr = a)

# 合并样本的实部和虚部
path1 = PATH+'d1/'
path2 = PATH+'d2/'
path3 = PATH+'d3/'
path4 = PATH+'d4/'
path5 = PATH+'d5/'
path6 = PATH+'d6/'
path7 = PATH+'d7/'
path8 = PATH+'d8/'
path9 = PATH+'d9/'
path10 = PATH+'d10/'

img_generate(real10, imag10, path1, 0, 300)
img_generate(real10, imag10, path2, 300, 600)
img_generate(real10, imag10, path3, 600, 900)
img_generate(real10, imag10, path4, 900, 1200)
img_generate(real10, imag10, path5, 1200, 1500)
img_generate(real10, imag10, path6, 1500, 1800)
img_generate(real10, imag10, path7, 1800, 2100)
img_generate(real10, imag10, path8, 2100, 2400)
img_generate(real10, imag10, path9, 2400, 2700)
img_generate(real10, imag10, path10, 2700, 3000)

[[0.82557827 1.4321059  1.47463173 ... 1.05496192 0.92484242 0.80275968]
 [0.68125671 1.60320759 1.71495575 ... 1.07316878 0.7635763  0.41190653]
 [0.48842415 1.08932218 1.34493154 ... 1.17032659 0.82532734 0.56598771]
 ...
 [0.0345986  0.13973739 0.20397902 ... 0.56591955 0.56591955 0.34003052]
 [0.04567134 0.14047819 0.18944099 ... 0.21560882 0.16266545 0.14291906]
 [0.04886629 0.11256145 0.14546387 ... 0.18650004 0.13817259 0.05894649]]


In [59]:
# 10段都有的就是组合实部虚部之后的原始数据

### 处理样本随机置零的部分
- 每种情况每个类选取100个样本
- 样本总数$n = 100 * 10 * 10 = 10000$

In [453]:
# N = 3
# pos = random.sample(range(0,10),N)
# pos

In [454]:
# ## test function set_zero
# path1 = './Spatial/non_zero_vector/30db/d1/392.npy'
# path2 = './Spatial/zero_vector/s8/d1/392.npy'
# arr = np.load(path1)
# set_zero(arr,path2)


In [203]:
# # 测试一下结果是不是我想要的
# arr1 = np.load(path2)
# print(arr[4095])


In [3]:
# get all the files of the path,读取文件夹下所有文件名字到一个列表
def readname(filePath):
    # 这里一定要使用绝对路径
    name = os.listdir(filePath)
    return name

In [40]:
#列表中随机抽取100个不重复的元素
def selectRandom(names):
    return np.random.choice(names, 100, False)

In [360]:
# 读取每个类别下的完整样本
filePath = '/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/'
folder_names = readname(filePath) #这里一定要使用绝对路径
# del folder_names[0] 
print(folder_names)

['d9', 'd7', 'd1', 'd6', 'd8', 'd10', 'd3', 'd4', 'd5', 'd2']


In [326]:
# 进行随机数据段置0
# 选择1～10的一个数N
# 从0～9随机选择n个数，记为数组nums[N]
# 对数组循环，置零0*nums[N]
def set_zero(arr, save_path,n):
    N = n
    pos = random.sample(range(0,10),N) # generate distinct N numbers
    print(pos)
    for num in pos:
        begin = num * 1024
        end = (num+1)*1024
        # print(begin)
        # print(end)
        for i in range(begin,end):
            arr[i] = [0,0];
    np.save(file = save_path,arr = arr)    

In [361]:
# des_PATH = './Spatial/zero_vector/s1/d1/'
merge_PATH = './Spatial/test_dataset/0db/'
# path = folder_names[0]+'/s1_'+folder_names[1]
# print(path)
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s10_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 0)
        
# name = selectRandom(names)
# print(name)
# s9
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s9_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 1)

# s8         
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s8_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 2)
        
# s7
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s7_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 3)
        
# s6
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s6_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 4)
        
# s5

for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s5_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 5)
        
# s4
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s4_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 6)
        
# s3
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s3_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 7)
        
# s2
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s2_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 8)
        
#s1
for folder in folder_names:
    folder_path = filePath + folder
    # print(folder_path)
    file_names = readname(folder_path)
    file_name = selectRandom(file_names)
    # print(file_name)
    for name in file_name:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s1_' + name
        arr = np.load(src_path)
        set_zero(arr, merge_path, 9)

/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2498.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2510.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2585.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2684.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2653.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2452.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2497.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2438.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2461.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2539.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2484.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d9/2572.npy
[]
/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/0db/d

In [595]:
# 这是我处理训练集的时候写的程序，但是觉得分开写有点费手
src_PATH = './Spatial/non_zero_vector/30db/d1/'
des_PATH = './Spatial/zero_vector/s1/d1/'
merge_PATH = './Spatial/merge_dataset/d1/s1_'
for i in name:
    print(i)
    src_path = (src_PATH + i)
    save_path = (des_PATH + i)
    merge_path = (merge_PATH + i)
    # print(merge_path)
    # print(des_PATH+i)
    arr = np.load(src_path)
    set_zero(arr, save_path)
    np.save(file = save_path,arr=arr)
    np.save(file = merge_path,arr = arr)
    

9065.npy
9327.npy
9951.npy
9604.npy
9518.npy
9354.npy
9345.npy
9115.npy
9725.npy
9930.npy
9264.npy
9437.npy
9035.npy
9821.npy
9474.npy
9080.npy
9872.npy
9662.npy
9724.npy
9487.npy
9246.npy
9540.npy
9651.npy
9966.npy
9017.npy
9198.npy
9046.npy
9395.npy
9780.npy
9816.npy
9533.npy
9844.npy
9616.npy
9220.npy
9371.npy
9827.npy
9853.npy
9548.npy
9773.npy
9635.npy
9256.npy
9416.npy
9185.npy
9947.npy
9915.npy
9963.npy
9769.npy
9447.npy
9143.npy
9589.npy
9632.npy
9734.npy
9306.npy
9097.npy
9608.npy
9387.npy
9273.npy
9492.npy
9835.npy
9045.npy
9858.npy
9682.npy
9311.npy
9167.npy
9108.npy
9478.npy
9094.npy
9605.npy
9224.npy
9545.npy
9054.npy
9648.npy
9194.npy
9599.npy
9923.npy
9394.npy
9445.npy
9333.npy
9663.npy
9053.npy
9132.npy
9049.npy
9891.npy
9326.npy
9173.npy
9864.npy
9566.npy
9204.npy
9945.npy
9538.npy
9706.npy
9028.npy
9641.npy
9461.npy
9217.npy
9960.npy
9784.npy
9544.npy
9624.npy
9694.npy


In [191]:
path2 = './Spatial/test_dataset/23db/d2/s10_371.npy'
arr1 = np.load(path2)
print(arr)

[[0.4245311  1.13955462]
 [0.871337   2.29435802]
 [0.871337   2.29435802]
 ...
 [0.24343476 2.04173875]
 [0.13849178 1.99714035]
 [0.03742642 1.95834589]]


In [567]:
## 之前没有merge进混合数据集的数据

mergeFilePath = '/Users/hurrican/Desktop/experiment/Spatial/zero_vector/s9/d1/'
merge_set = './Spatial/merge_dataset/d1/s9_'
filesname = readname(mergeFilePath)
for i in filesname:
    arr = np.load(mergeFilePath+i)
    np.save(file = merge_set+i,arr = arr)


['d9', 'd7', 'd1', 'd6', 'd8', 'd10', 'd3', 'd4', 'd5', 'd2']


In [8]:
slice_PATH = './Spatial/slice_data/30db/d1/'
# slice1_PATH = 
for folder in folder_names:
    folder_path = filePath + folder
    print(folder_path)
    file_names = readname(folder_path)
    for file_name in file_names:
        src_path = folder_path + '/'+ name
        print(src_path)
        # save_path = des_PATH + folder +name
        merge_path = merge_PATH +folder + '/s10_' + name
        arr = np.load(src_path)
        

/Users/hurrican/Desktop/experiment/Spatial/non_zero_vector/30db/d9
['8081.npy', '8095.npy', '8903.npy', '8917.npy', '8724.npy', '8042.npy', '8056.npy', '8730.npy', '8718.npy', '8283.npy', '8297.npy', '8240.npy', '8526.npy', '8532.npy', '8254.npy', '8268.npy', '8491.npy', '8485.npy', '8334.npy', '8452.npy', '8446.npy', '8320.npy', '8308.npy', '8693.npy', '8687.npy', '8877.npy', '8863.npy', '8888.npy', '8650.npy', '8136.npy', '8122.npy', '8644.npy', '8678.npy', '8679.npy', '8123.npy', '8645.npy', '8651.npy', '8889.npy', '8137.npy', '8862.npy', '8876.npy', '8686.npy', '8692.npy', '8309.npy', '8447.npy', '8321.npy', '8335.npy', '8453.npy', '8484.npy', '8490.npy', '8269.npy', '8533.npy', '8255.npy', '8241.npy', '8527.npy', '8296.npy', '8282.npy', '8719.npy', '8057.npy', '8731.npy', '8725.npy', '8043.npy', '8916.npy', '8902.npy', '8094.npy', '8080.npy', '8928.npy', '8096.npy', '8082.npy', '8914.npy', '8900.npy', '8733.npy', '8055.npy', '8041.npy', '8727.npy', '8069.npy', '8294.npy', '8280.np